package umich.eecs441.project.proto;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: remove_command_buf.proto

public final class RemoveCommandBuf {
  private RemoveCommandBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RemoveCommandBufObjOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 clientID = 1;
    /**
     * <code>required int32 clientID = 1;</code>
     */
    boolean hasClientID();
    /**
     * <code>required int32 clientID = 1;</code>
     */
    int getClientID();

    // required string removedChar = 2;
    /**
     * <code>required string removedChar = 2;</code>
     */
    boolean hasRemovedChar();
    /**
     * <code>required string removedChar = 2;</code>
     */
    java.lang.String getRemovedChar();
    /**
     * <code>required string removedChar = 2;</code>
     */
    com.google.protobuf.ByteString
        getRemovedCharBytes();
  }
  /**
   * Protobuf type {@code RemoveCommandBufObj}
   */
  public static final class RemoveCommandBufObj extends
      com.google.protobuf.GeneratedMessage
      implements RemoveCommandBufObjOrBuilder {
    // Use RemoveCommandBufObj.newBuilder() to construct.
    private RemoveCommandBufObj(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RemoveCommandBufObj(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RemoveCommandBufObj defaultInstance;
    public static RemoveCommandBufObj getDefaultInstance() {
      return defaultInstance;
    }

    public RemoveCommandBufObj getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RemoveCommandBufObj(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              clientID_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              removedChar_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RemoveCommandBuf.internal_static_RemoveCommandBufObj_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RemoveCommandBuf.internal_static_RemoveCommandBufObj_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RemoveCommandBuf.RemoveCommandBufObj.class, RemoveCommandBuf.RemoveCommandBufObj.Builder.class);
    }

    public static com.google.protobuf.Parser<RemoveCommandBufObj> PARSER =
        new com.google.protobuf.AbstractParser<RemoveCommandBufObj>() {
      public RemoveCommandBufObj parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RemoveCommandBufObj(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RemoveCommandBufObj> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 clientID = 1;
    public static final int CLIENTID_FIELD_NUMBER = 1;
    private int clientID_;
    /**
     * <code>required int32 clientID = 1;</code>
     */
    public boolean hasClientID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 clientID = 1;</code>
     */
    public int getClientID() {
      return clientID_;
    }

    // required string removedChar = 2;
    public static final int REMOVEDCHAR_FIELD_NUMBER = 2;
    private java.lang.Object removedChar_;
    /**
     * <code>required string removedChar = 2;</code>
     */
    public boolean hasRemovedChar() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string removedChar = 2;</code>
     */
    public java.lang.String getRemovedChar() {
      java.lang.Object ref = removedChar_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          removedChar_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string removedChar = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRemovedCharBytes() {
      java.lang.Object ref = removedChar_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        removedChar_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      clientID_ = 0;
      removedChar_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasClientID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRemovedChar()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, clientID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getRemovedCharBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, clientID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getRemovedCharBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static RemoveCommandBuf.RemoveCommandBufObj parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RemoveCommandBuf.RemoveCommandBufObj parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RemoveCommandBuf.RemoveCommandBufObj parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RemoveCommandBuf.RemoveCommandBufObj parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RemoveCommandBuf.RemoveCommandBufObj parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static RemoveCommandBuf.RemoveCommandBufObj parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static RemoveCommandBuf.RemoveCommandBufObj parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static RemoveCommandBuf.RemoveCommandBufObj parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static RemoveCommandBuf.RemoveCommandBufObj parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static RemoveCommandBuf.RemoveCommandBufObj parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(RemoveCommandBuf.RemoveCommandBufObj prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RemoveCommandBufObj}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements RemoveCommandBuf.RemoveCommandBufObjOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RemoveCommandBuf.internal_static_RemoveCommandBufObj_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RemoveCommandBuf.internal_static_RemoveCommandBufObj_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RemoveCommandBuf.RemoveCommandBufObj.class, RemoveCommandBuf.RemoveCommandBufObj.Builder.class);
      }

      // Construct using RemoveCommandBuf.RemoveCommandBufObj.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        clientID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        removedChar_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RemoveCommandBuf.internal_static_RemoveCommandBufObj_descriptor;
      }

      public RemoveCommandBuf.RemoveCommandBufObj getDefaultInstanceForType() {
        return RemoveCommandBuf.RemoveCommandBufObj.getDefaultInstance();
      }

      public RemoveCommandBuf.RemoveCommandBufObj build() {
        RemoveCommandBuf.RemoveCommandBufObj result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public RemoveCommandBuf.RemoveCommandBufObj buildPartial() {
        RemoveCommandBuf.RemoveCommandBufObj result = new RemoveCommandBuf.RemoveCommandBufObj(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.clientID_ = clientID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.removedChar_ = removedChar_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RemoveCommandBuf.RemoveCommandBufObj) {
          return mergeFrom((RemoveCommandBuf.RemoveCommandBufObj)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RemoveCommandBuf.RemoveCommandBufObj other) {
        if (other == RemoveCommandBuf.RemoveCommandBufObj.getDefaultInstance()) return this;
        if (other.hasClientID()) {
          setClientID(other.getClientID());
        }
        if (other.hasRemovedChar()) {
          bitField0_ |= 0x00000002;
          removedChar_ = other.removedChar_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasClientID()) {
          
          return false;
        }
        if (!hasRemovedChar()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RemoveCommandBuf.RemoveCommandBufObj parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RemoveCommandBuf.RemoveCommandBufObj) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 clientID = 1;
      private int clientID_ ;
      /**
       * <code>required int32 clientID = 1;</code>
       */
      public boolean hasClientID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 clientID = 1;</code>
       */
      public int getClientID() {
        return clientID_;
      }
      /**
       * <code>required int32 clientID = 1;</code>
       */
      public Builder setClientID(int value) {
        bitField0_ |= 0x00000001;
        clientID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 clientID = 1;</code>
       */
      public Builder clearClientID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        clientID_ = 0;
        onChanged();
        return this;
      }

      // required string removedChar = 2;
      private java.lang.Object removedChar_ = "";
      /**
       * <code>required string removedChar = 2;</code>
       */
      public boolean hasRemovedChar() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string removedChar = 2;</code>
       */
      public java.lang.String getRemovedChar() {
        java.lang.Object ref = removedChar_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          removedChar_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string removedChar = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRemovedCharBytes() {
        java.lang.Object ref = removedChar_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          removedChar_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string removedChar = 2;</code>
       */
      public Builder setRemovedChar(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        removedChar_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string removedChar = 2;</code>
       */
      public Builder clearRemovedChar() {
        bitField0_ = (bitField0_ & ~0x00000002);
        removedChar_ = getDefaultInstance().getRemovedChar();
        onChanged();
        return this;
      }
      /**
       * <code>required string removedChar = 2;</code>
       */
      public Builder setRemovedCharBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        removedChar_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RemoveCommandBufObj)
    }

    static {
      defaultInstance = new RemoveCommandBufObj(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RemoveCommandBufObj)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RemoveCommandBufObj_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RemoveCommandBufObj_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030remove_command_buf.proto\"<\n\023RemoveComm" +
      "andBufObj\022\020\n\010clientID\030\001 \002(\005\022\023\n\013removedCh" +
      "ar\030\002 \002(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_RemoveCommandBufObj_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_RemoveCommandBufObj_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RemoveCommandBufObj_descriptor,
              new java.lang.String[] { "ClientID", "RemovedChar", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
